# config.yaml

model:
  name: "DeepLabV3-Plus"
  input_channels: 5
  output_channels: 1
  model_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/deeplabv3_plus"

data:
  dataset_path: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/input/updated_samples/multi_channel_segnet_512"
  image_size:
    height: 512
    width: 512
  channels: [0, 1, 2, 4, 5]
  batch_size: 4
  buffer_size: 100
  seed: 42
  enable_op_determinism: false
  test_size: 0.2
  augmentation:
    rotate: true
    flip_horizontal: true
    zoom_range: 0.1

training:
  epochs: 100
  learning_rate: 0.0001
  optimizer: "Adam"
  training_split: 0.2
  checkpoint_callback:
    monitor: "val_accuracy"
    mode: "max"
    save_best_only: true
    save_weights_only: false
  early_stopping_callback:
    monitor: "val_loss"
    mode: "min"
    patience: 10
    restore_best_weights: true

plots:
  display: false

paths:
  model_save_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/deeplabv3_plus/ckpt"
  log_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/deeplabv3_plus/logs"
  output_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/deeplabv3_plus/output"
  saved_file_name: "model_6_channels.h5"
