# config.yaml

model:
  name: "SegNet-VGG16"
  input_channels: 3
  output_channels: 1
  model_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/segnet_VGG16"

data:
  dataset_path: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/input/dataset"
  image_size:
    height: 512
    width: 512
  channels: ["RED", "GREEN", "BLUE"]
  batch_size: 4
  buffer_size: 100
  seed: 42
  enable_op_determinism: false
  test_size: 0.2
  augmentation:
    rotate: true
    flip_horizontal: true
    zoom_range: 0.1

training:
  epochs: 100
  learning_rate: 0.0001
  enable_reduce_on_plateau: false
  optimizer: "Adam"
  training_split: 0.2
  checkpoint_callback:
    monitor: "val_accuracy"
    mode: "max"
    save_best_only: true
    save_weights_only: false
  early_stopping_callback:
    monitor: "val_loss"
    mode: "min"
    patience: 10
    restore_best_weights: true

plots:
  display: false

paths:
  model_save_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/segnet_VGG16/ckpt"
  log_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/segnet_VGG16/logs"
  output_dir: "C:/Users/AdikariAdikari/PycharmProjects/Segmentation/models/segnet_VGG16/output"
  saved_file_name: "model_3_channels"
