# config.yaml

model:
  name: "Unet"
  input_channels: 3
  output_channels: 1

data:
  dataset_path: "../../input/samples/segnet_512/images"
  image_size: [512, 512]
  batch_size: 4
  augmentation:
    rotate: true
    flip_horizontal: true
    zoom_range: 0.1

training:
  epochs: 100
  learning_rate: 0.0001
  optimizer: "Adam"
  training_split: 0.2

paths:
  model_save_dir: "./ckpt"
  log_dir: "./logs"
  output_dir: "./output"